name: Main workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run code
        run: python main.py
  bump_version:
    runs-on: ubuntu-latest
    needs: build
    name: 'Bump version and create changelog with commitizen'
    steps:
      - uses: actions/checkout@v3
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.15.1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: "${{ env.REVISION }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
