name: Main workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    uses: manhinhang/python-template/.github/workflows/test.yaml@main
  bump_version:
    runs-on: ubuntu-latest
    needs: build
    name: 'Bump version and create changelog with commitizen'
    steps:
      - uses: actions/checkout@v3
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.15.1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: "${{ env.REVISION }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
